# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal
email: yanalves@hotmail.com
description: "Este é um blog minimalista criado para aprender como funciona essa ferramenta linda que é o Jekyll"
baseurl: "minimal-blog" # the subpath of your site, e.g. /blog
url: "http://yanalves.com.br" # the base hostname & protocol for your site
twitter_username: yantwo
github_username:  yalves

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
# permalink: /:year/:month/:day/:title
permalink: /:title